title: Ukeje Okoronkwo's Portfolio
email: okoronkwouk@gmail.com
baseurl: "" 
url: "https://ukejeo.github.io"
theme: minima

collections:
  projects:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
